### ISSUE TITLE
 Turn on file search?

### ISSUE THREAD

**Issue by aetaf** [awesometic/docker-h5ai#1]
"search": {
     "enabled": true,
     "advanced": true,
     "debounceTime": 300,
     "ignorecase": true
 },

     "enabled": false,  change  true

Did not take effect, what should I do?

**Comment by awesometic** [comment]
Hi,

I just have tested the searching feature by editing _h5ai/private/conf/options.json file.
Actually it does work on my side :0
After replacing "enabled" to true, a magnifier icon appears on the top bar of the websites.
I think you should check cache things on your browser. :)

**Comment by awesometic** [comment]
I'll close this issue.

And it is better that you ask an issue to the official h5ai repository: https://github.com/lrsjng/h5ai
Anyway, thanks to your active feedback. :)
