### ISSUE TITLE
webm thumbnail failure

### ISSUE THREAD

**Issue by breadcat** [awesometic/docker-h5ai#13]
Hello there, I've recently replaced `corfr/h5ai` with your container but have noticed that I no longer get thumbnails for webm files.
When I click them to preview the file fullscreen, it will work fine (at least in my browser, Firefox).

The error I'm getting via `docker logs` when requested is as follows:
```
172.18.0.12 - - [11/Nov/2021:16:39:34 +0000] "GET directory/file.webm HTTP/1.1" 206 131147 "https://domain/directory/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0" "myip"
2021/11/11 16:43:17 [error] 41#41: *87 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) in /config/h5ai/_h5ai/private/php/ext/class-thumb.php on line 148" while reading response header from upstream, client: 172.18.0.12, server: _, request: "POST /directory/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "domain", referrer: "https://domain/directory/"
```

**Comment by awesometic** [comment]
Hello. Sorry for the late reply.

Can you attach a sample `webm` file?
I can see a thumbnail of some sample `webm` files I downloaded from the Internet.
- https://file-examples.com/index.php/sample-video-files/sample-webm-files-download/
- https://www.webmfiles.org/demo-files/

![Screenshot_20211129_125327](https://user-images.githubusercontent.com/10906167/143806245-44460596-b9e6-475a-90fe-879bdb4c7c1f.png)

**Comment by breadcat** [comment]
Thanks for your reply, I've attached [an affected file.](https://github.com/awesometic/docker-h5ai/files/7642547/iron.zip).

It's strange, I've tried using two example files from your links above and both of these work absolutely fine.

I originally converted these files from gifs to webm to save space using `ffmpeg`, I have also issued `file *.webm` and all of them identify as WebM files. I assume this conversion process is where the issue will lay.

**Comment by awesometic** [comment]
I have looked into that, but I don't know what is the actual differences between the sample files from those sites and the one ffmpeg generated.

I converted a sample video file to a webm file, on my side, but these files are not providing a thumbnail either.
Here's what I tried to.
```
// VP8
ffmpeg -i /h5ai/sample.h264 -c:v libvpx -crf 30 -b:v 0 /h5ai/temp/vp8.webm

// VP9
ffmpeg -i /h5ai/sample.h264 -c:v libvpx-vp9 -crf 30 -b:v 0 /h5ai/temp/vp9.webm
```

Did you report this issue to the h5ai developer?

**Comment by breadcat** [comment]
Thanks for your reply, sorry for the long response.
I think it's safe to say that this isn't an issue with your container with the sample files working fine. I'll raise this either with ffmpeg or h5ai.

Thanks for your help.
