### ISSUE TITLE
Fatal Python error: init_interp_main: can't initialize time

### ISSUE THREAD

**Issue by sshuangliu** [awesometic/docker-h5ai#16]
my env :
pi 3 B+ 
armv7 32

docker run -d --name=h5ai \
-p 801:80 \
-v /mnt/usb_flash/Aria2/aria2-downloads:/h5ai/aria2-downloads \
-v /mnt/usb_flash/resilio-sync:/h5ai/resilio-sync \
-v /mnt/usb_flash/h5ai-config:/config \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=Asia/Shanghai \
--restart unless-stopped \
awesometic/h5ai

then I got some errors by logs and restart Automatically every 2 sec

logs:

Variables:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Shanghai
        - HTPASSWD=false
        - HTPASSWD_USER=guest
        - HTPASSWD_PW=
Configure timezone for PHP...
Make config directories...
Add dummy user for better handle permission...
Check configuration files for Nginx...
User setup files found: /config/nginx/h5ai.conf
Remove image's default setup files and copy the previous version...
Check configuration files for h5ai...
User setup files found: /config/h5ai/_h5ai
Check if h5ai version updated...
Remove image's default setup files and copy the existing version...
Set permission for caching...
Fix ownership for Nginx and php-fpm...
Set ownership to the configuration files...
Start supervisord...
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0x76f85390 (most recent call first):
<no Python frame>
Variables:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Shanghai
        - HTPASSWD=false
        - HTPASSWD_USER=guest
        - HTPASSWD_PW=
Make config directories...
Add dummy user for better handle permission...
useradd: user 'abc' already exists
usermod: no changes
Check configuration files for Nginx...
User setup files found: /config/nginx/h5ai.conf
Remove image's default setup files and copy the previous version...
Check configuration files for h5ai...
User setup files found: /config/h5ai/_h5ai
Check if h5ai version updated...
Remove image's default setup files and copy the existing version...
Set permission for caching...
Fix ownership for Nginx and php-fpm...
Set ownership to the configuration files...
Start supervisord...
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

what might be happened there and why ?
I have no idea about that....

thanks

**Comment by awesometic** [comment]
Hello,
Sorry for the late reply.

Actually, it seems like it isn't an issue related to this Docker image.
What's your OS and kernel version? I found some information about RaspberryPi and Docker with Google.
What I found so far for the common workaround, you can try updating your libseccomp packages.

```sh
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.3-2_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp-dev_2.5.3-2_armhf.deb
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/seccomp_2.5.3-2_armhf.deb
sudo dpkg -i *seccomp*
```

Please refer to this link too: https://docs.linuxserver.io/faq#libseccomp

**Comment by sshuangliu** [comment]
> 
after did thoes operation refer to the link which you gave then it works, you are the best :

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2`



many thanks

below are some useful information for others guys maybe :


pi@raspberrypi:/mnt/usb_flash$ docker -v
Docker version 20.10.12, build e91ed57
pi@raspberrypi:/mnt/usb_flash$ uname -an
Linux raspberrypi 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021 armv7l GNU/Linux

pi@raspberrypi:/mnt/usb_flash$ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
