### ISSUE TITLE
multiple users

### ISSUE THREAD

**Issue by lephtHanded** [awesometic/docker-h5ai#18]
not an issue, this works great!
I use it to share photos with my family.
Anyway to add more unique users/passwords?

**Comment by awesometic** [comment]
Hello,

We can add more users by using `htpasswd` command.

Get the container's shell and try to add the users.

```bash
docker exec -it {H5AI_CONTAINER_NAME} /bin/bash
```

Then add a user using `htpasswd` command. Here's our case.

```bash
htpasswd /config/nginx/.htpasswd {NEW_USER_NAME}
```

Then, in my test environment, I can see multiple users in the `/config/nginx/.htpasswd` file.

```bash
$ cat /config/nginx/.htpasswd
guest:$apr1$w0Vseerb$dFLDY...
awesometic:$apr1$yqTtlN9h$FCRn...
```

You can see further information here: https://httpd.apache.org/docs/current/en/programs/htpasswd.html

Please try this and let me know the results. 😃

**Comment by lephtHanded** [comment]
this worked great!
thank you so much!

**Comment by awesometic** [comment]
Thanks for confirming. 😄
