### ISSUE TITLE
Using Reverse Proxy for TLS?

### ISSUE THREAD

**Issue by clementperon** [awesometic/docker-h5ai#2]
Hi, 

Instead of implementing Let's encrypt inside this docker what about being compatible with a reverse proxy. e.g: https://github.com/linuxserver/docker-letsencrypt

Thanks

**Comment by awesometic** [comment]
Hi,

Actually this docker image already supports SSL/TLS with an external reverse proxy server. :)
Even I'm running services using a docker-compose.yml file that includes this h5ai and the central Let's encrypt for a reverse proxy to all of the incoming subdomain requests.

Please refer to https://github.com/awesometic/docker-h5ai#todos

Thanks for your feedback. I'll close this issue if this answer is helpful for you. :)

**Comment by clementperon** [comment]
Hi,

Sorry I didn't precise but i'm doing reverse proxy with subfolder not subdomain.
Looks like H5AI is not compatible with subfolder reverse proxy :(

Do you have an nginx example for subdomain reverse proxy ?

Thanks,
Clement

**Comment by clementperon** [comment]
Okay got it working nice with subdomain !
