### ISSUE TITLE
Thumbnails not displaying due to low PHP memory limit

### ISSUE THREAD

**Issue by fib** [awesometic/docker-h5ai#24]
Hi, I just installed this image and everything worked fine, except for file preview thumbnails. I was able to fix this by editing the `memory_limit` setting in `/etc/php8/php.ini` to `-1` (unlimited):

```bash
sed -i -e '/memory_limit =/ s/= .*/= -1/' /etc/php8/php.ini
```

If you think this should be the default value then I could PR this (what would be the appropriate step to perform this in? `Dockerfile` or `init.sh`?). Thanks!

**Comment by awesometic** [comment]
Hi, sorry for the really late reply. I saw your post and thought that reply to it later but I forgot 😅 

And thank you for your suggestion. You can create `config/php_set_memory_limit.ini` and apply it similarly to the other PHP config files.

Please make PR, and I will review and merge that. :)
