### ISSUE TITLE
recommend to add resume download function

### ISSUE THREAD

**Issue by suqin-haha** [awesometic/docker-h5ai#3]
Hi, 
nice docker!, recommend to add resume download function

Thankyou

**Comment by awesometic** [comment]
Hi.

Yes that feature, I'd want to, but the main project that this Docker image has been using is maintained by the official h5ai developer. 
Please visit his [Github repository](https://github.com/lrsjng/h5ai) and ask the new feature. :)

I'll close this issue. Thanks.
