### ISSUE TITLE
PUID and PGID env variables have no effect

### ISSUE THREAD

**Issue by rdcavanha** [awesometic/docker-h5ai#8]
Hello,

Using the env variables PUID and PGID has no effect. 

To replicate the issue:
* Map volume that contains files with permission 770 to `/h5ai`
* Run the container passing the PUID and PGID env variables to match the owner's of the mapped volume
* Result: files are not seen by h5ai

If I instead chmod the mapped volume to 774, h5ai is able to see my files. As far as I know, the container should be able to see my files without chmoding the mapped volume to allow others to see them. Emby's image (https://hub.docker.com/r/linuxserver/emby) seems to manage that the right way.

**Comment by awesometic** [comment]
Thank you for the detailed feedback.
Honestly, I didn't think of that permission management.

I will look into this and will let you know the results. 😃

**Comment by awesometic** [comment]
Sorry for the too-late update.

I have tested on my side with the newly implemented PUID/PGID handling. The images on the Docker hub will be updated soon so please test with the new image. If there's an issue then let me know with the new issue thread. :smile:
